const subjectList = {
  1: {
    CSE: [
      { PAPERNAME: "PHYSICS", PAPERCODE: " BS - PH101" },
      { PAPERNAME: "MATHEMATICS-IA", PAPERCODE: " BS - M101 " },
      { PAPERNAME: "BASIC ELECTRICAL ENGINEERING", PAPERCODE: "ES-EE101" },
      { PAPERNAME: "PHYSICS-1LAB", PAPERCODE: "BS-PH191" },
      {
        PAPERNAME: "BASIC ELECTRICAL ENGINEERING LAB",
        PAPERCODE: "ES-EE191",
      },
      { PAPERNAME: "MANUFACTURING WORKSHOP", PAPERCODE: "ES-ME191" },
    ],
    ME: [
      { PAPERNAME: "PHYSICS", PAPERCODE: " BS - PH101 " },
      { PAPERNAME: "MATHEMATICS-IA", PAPERCODE: " BS - M101 " },
      { PAPERNAME: "BASIC ELECTRICAL ENGINEERING", PAPERCODE: "ES-EE101" },
      { PAPERNAME: "PHYSICS-1LAB", PAPERCODE: " BS - PH191 " },
      {
        PAPERNAME: "BASIC ELECTRICAL ENGINEERING LAB",
        PAPERCODE: "ES-EE191",
      },
      { PAPERNAME: "MANUFACTURING WORKSHOP", PAPERCODE: " ES - ME191 " },
    ],
    ECE: [
      { PAPERNAME: "CHEMISTRY-I", PAPERCODE: "BS-CH101" },
      { PAPERNAME: "MATHEMATICS-IB", PAPERCODE: "BS-M102" },
      { PAPERNAME: "BASIC ELECTRICAL ENGINEERING", PAPERCODE: "ES-EE101" },
      { PAPERNAME: "CHEMISTRY-1LAB", PAPERCODE: "BS-CH191" },
      { PAPERNAME: "BASIC ELECTRICAL ENGINEERING LAB", PAPERCODE: "ES-EE191" },
      { PAPERNAME: "ENGINEERING GRAPHICS & DESIGN", PAPERCODE: "ES-ME191" },
    ],
    EE: [
      { PAPERNAME: "CHEMISTRY", PAPERCODE: "BS-CH101" },
      { PAPERNAME: "MATHEMATICS-IB", PAPERCODE: "BS-M102" },
      { PAPERNAME: "BASIC ELECTRICAL ENGINEERING", PAPERCODE: "ES-EE101" },
      { PAPERNAME: "CHEMISTRY-1LAB", PAPERCODE: "BS-CH191" },
      { PAPERNAME: "BASIC ELECTRICAL ENGINEERING LAB", PAPERCODE: "ES-EE191" },
      { PAPERNAME: "ENGINEERING GRAPHICS & DESIGN", PAPERCODE: "ES-ME191" },
    ],
    CSBS: [
      { PAPERNAME: "Discrete Mathematics", PAPERCODE: null },
      {
        PAPERNAME: "Introductory Topics in Statistics, Probability and",
        PAPERCODE: null,
      },
      { PAPERNAME: "Calculus", PAPERCODE: null },
      {
        PAPERNAME: "CS Fundamentals of Computer Science+ Lab",
        PAPERCODE: null,
      },
      {
        PAPERNAME: "Principles of Electrical Engineering + Lab",
        PAPERCODE: null,
      },
      { PAPERNAME: "Fundamentals of Physics+ Lab ", PAPERCODE: null },
      {
        PAPERNAME: "Business Communication & Value Science - I",
        PAPERCODE: null,
      },
      { PAPERNAME: "Induction Program", PAPERCODE: null },
    ],
    EEE: [
      { PAPERNAME: "CHEMISTRY-I", PAPERCODE: "BS-CH101" },
      { PAPERNAME: "MATHEMATICS-IB", PAPERCODE: "BS-M102" },
      { PAPERNAME: "BASIC ELECTRICAL ENGINEERING", PAPERCODE: "ES-EE101" },
      { PAPERNAME: "CHEMISTRY-1LAB", PAPERCODE: "BS-CH191" },
      { PAPERNAME: "BASIC ELECTRICAL ENGINEERING LAB", PAPERCODE: "ES-EE191" },
      { PAPERNAME: "ENGINEERING GRAPHICS & DESIGN", PAPERCODE: "ES-ME191" },
    ],
  },
  2: {
    CSE: [
      { PAPERNAME: "CHEMISTRY", PAPERCODE: "BS-CH201" },
      { PAPERNAME: "MATHEMATICS-IIA", PAPERCODE: "BS-M201" },
      { PAPERNAME: "PROGRAMMING FOR PROBLEM SOLVING", PAPERCODE: "ES-CS201" },
      { PAPERNAME: "ENGLISH", PAPERCODE: "HM-HU201" },
      { PAPERNAME: "CHEMISTRY-1LAB", PAPERCODE: "BS-CH291" },
      {
        PAPERNAME: "PROGRAMMING FOR PROBLEM SOLVING LAB",
        PAPERCODE: "ES-CS291",
      },
      { PAPERNAME: "ENGINEERING GRAPHICS & DESIGN", PAPERCODE: "ES-ME291" },
      { PAPERNAME: "LANGUAGE LABRATORY", PAPERCODE: "HM-HU291" },
    ],
    CSBS: [
      { PAPERNAME: "Linear Algebra", PAPERCODE: null },
      { PAPERNAME: "Statistical Methods + Lab", PAPERCODE: null },
      { PAPERNAME: "Data Structures & Algorithms+ Lab", PAPERCODE: null },
      { PAPERNAME: "Principles of Electronics + Lab", PAPERCODE: null },
      { PAPERNAME: "Fundamentals of Economics", PAPERCODE: null },
      {
        PAPERNAME: "Business Communication & Value Science – II",
        PAPERCODE: null,
      },
      { PAPERNAME: "Environmental Sciences", PAPERCODE: null },
    ],
    ME: [
      { PAPERNAME: "CHEMISTRY", PAPERCODE: "BS-CH201" },
      { PAPERNAME: "MATHEMATICS-IIA", PAPERCODE: "BS-M201" },
      { PAPERNAME: "PROGRAMMING FOR PROBLEM SOLVING", PAPERCODE: "ES-CS201" },
      { PAPERNAME: "ENGLISH", PAPERCODE: "HM-HU201" },
      { PAPERNAME: "CHEMISTRY-1LAB", PAPERCODE: "BS-CH291" },
      {
        PAPERNAME: "PROGRAMMING FOR PROBLEM SOLVING LAB",
        PAPERCODE: "ES-CS291",
      },
      { PAPERNAME: "ENGINEERING GRAPHICS & DESIGN", PAPERCODE: "ES-ME291" },
      { PAPERNAME: "LANGUAGE LABRATORY", PAPERCODE: "HM-HU291" },
    ],
    ECE: [
      { PAPERNAME: "PHYSICS", PAPERCODE: "BS-PH201" },
      { PAPERNAME: "MATHEMATICS-IIB", PAPERCODE: "BS-M202" },
      { PAPERNAME: "PROGRAMMING FOR PROBLEM SOLVING", PAPERCODE: "ES-CS201" },
      { PAPERNAME: "ENGLISH", PAPERCODE: "HM-HU201" },
      { PAPERNAME: "PHYSICS-1LAB", PAPERCODE: "BS-PH291" },
      {
        PAPERNAME: "PROGRAMMING FOR PROBLEM SOLVING LAB",
        PAPERCODE: "ES-CS291",
      },
      { PAPERNAME: "MANUFACTURING LAB", PAPERCODE: "ES-ME292" },
      { PAPERNAME: "LANGUAGE LABRATORY", PAPERCODE: "HM-HU291" },
    ],
    EE: [
      { PAPERNAME: "PHYSICS", PAPERCODE: "BS-PH201" },
      { PAPERNAME: "MATHEMATICS-IIB", PAPERCODE: "BS-M202" },
      { PAPERNAME: "PROGRAMMING FOR PROBLEM SOLVING", PAPERCODE: "ES-CS201" },
      { PAPERNAME: "ENGLISH", PAPERCODE: "HM-HU201" },
      { PAPERNAME: "PHYSICS-1LAB", PAPERCODE: "BS-PH291" },
      {
        PAPERNAME: "PROGRAMMING FOR PROBLEM SOLVING LAB",
        PAPERCODE: "ES-CS291",
      },
      { PAPERNAME: "MANUFACTURING LAB", PAPERCODE: "ES-ME292" },
      { PAPERNAME: "LANGUAGE LABRATORY", PAPERCODE: "HM-HU291" },
    ],
    EEE: [
      { PAPERNAME: "PHYSICS", PAPERCODE: "BS-PH201" },
      { PAPERNAME: "MATHEMATICS-IIB", PAPERCODE: "BS-M202" },
      { PAPERNAME: "PROGRAMMING FOR PROBLEM SOLVING", PAPERCODE: "ES-CS201" },
      { PAPERNAME: "ENGLISH", PAPERCODE: "HM-HU201" },
      { PAPERNAME: "PHYSICS-1LAB", PAPERCODE: "BS-PH291" },
      {
        PAPERNAME: "PROGRAMMING FOR PROBLEM SOLVING LAB",
        PAPERCODE: "ES-CS291",
      },
      { PAPERNAME: "MANUFACTURING LAB", PAPERCODE: "ES-ME292" },
      { PAPERNAME: "LANGUAGE LABRATORY", PAPERCODE: "HM-HU291" },
    ],
  },
  3: {
    CSE: [
      { PAPERNAME: "ANALOG AND DIGITAL ELECTRONICS", PAPERCODE: "ESC-301" },
      { PAPERNAME: "DATA STRUCTURE AND ALGORITHM", PAPERCODE: "PCC-CS301" },
      { PAPERNAME: "COMPUTER ORGANISATION", PAPERCODE: "PCC-CS302" },
      { PAPERNAME: "MATHEMATICS-III", PAPERCODE: "BSC-301" },
      {
        PAPERNAME: "ECONOMICS FOR ENGINEERS(HUMANITIES-II)",
        PAPERCODE: "HSMC-301",
      },
      { PAPERNAME: "ANALOG AND DIGITAL ELECTRONICS LAB", PAPERCODE: "ESC-391" },
      { PAPERNAME: "DATA STRUCTURE AND ALGORITHM LAB", PAPERCODE: "PCC-CS391" },
      { PAPERNAME: "COMPUTER ORGANISATION LAB", PAPERCODE: "PCC-CS392" },
      { PAPERNAME: "IT WORKSHOP LAB", PAPERCODE: "PCC-CS393" },
    ],
    IT: [
      { PAPERNAME: "ANALOG AND DIGITAL ELECTRONICS", PAPERCODE: "ESC-301" },
      { PAPERNAME: "DATA STRUCTURE AND ALGORITHM", PAPERCODE: "PCC-CS301" },
      { PAPERNAME: "COMPUTER ORGANISATION", PAPERCODE: "PCC-CS302" },
      { PAPERNAME: "MATHEMATICS-III", PAPERCODE: "BSC-301" },
      {
        PAPERNAME: "ECONOMICS FOR ENGINEERS(HUMANITIES-II)",
        PAPERCODE: "HSMC-301",
      },
      { PAPERNAME: "ANALOG AND DIGITAL ELECTRONICS LAB", PAPERCODE: "ESC-391" },
      { PAPERNAME: "DATA STRUCTURE AND ALGORITHM LAB", PAPERCODE: "PCC-CS391" },
      { PAPERNAME: "COMPUTER ORGANISATION LAB", PAPERCODE: "PCC-CS392" },
      { PAPERNAME: "IT WORKSHOP LAB", PAPERCODE: "PCC-CS393" },
    ],
    CSBS: [
      { PAPERNAME: "Formal Language and Automata Theory", PAPERCODE: null },
      { PAPERNAME: "Computer Organization & Architecture", PAPERCODE: null },
      { PAPERNAME: "Object Oriented Programming + Lab", PAPERCODE: null },
      { PAPERNAME: "Computational Statistics + Lab", PAPERCODE: null },
      { PAPERNAME: "Software Engineering + Lab", PAPERCODE: null },
      { PAPERNAME: "Indian Constitution(Non Credit)", PAPERCODE: null },
    ],
    ME: [
      { PAPERNAME: " Mathematics-III", PAPERCODE: "BS-M301" },
      { PAPERNAME: "Biology", PAPERCODE: "BS-BIO301 " },
      { PAPERNAME: "Basic Electronics Engineering", PAPERCODE: "ES-ECE301 " },
      { PAPERNAME: "Engineering Mechanics ", PAPERCODE: "ES-ME301" },
      { PAPERNAME: "Thermodynamics ", PAPERCODE: "PC-ME301" },
      { PAPERNAME: "Manufacturing Processes", PAPERCODE: "PC-ME302 " },
      {
        PAPERNAME: "Practice of Manufacturing Processes",
        PAPERCODE: "PC-ME391 ",
      },
    ],
    ECE: [
      { PAPERNAME: "Electronic Devices", PAPERCODE: "EC301 " },
      { PAPERNAME: "Digital System Design", PAPERCODE: "EC302 " },
      { PAPERNAME: "Signals and System", PAPERCODE: "EC303" },
      { PAPERNAME: "Network Theory", PAPERCODE: "EC304 " },
      { PAPERNAME: "Data Structure & Algorithms", PAPERCODE: "ES-CS301 " },
      { PAPERNAME: "Probality and Satistics ", PAPERCODE: "BS-M301 " },
      { PAPERNAME: "Environmental Science ", PAPERCODE: "MC381 " },
      { PAPERNAME: "Electronics Devices Lab", PAPERCODE: "EC391 " },
      { PAPERNAME: "Digital System Design Lab ", PAPERCODE: "EC392" },
      { PAPERNAME: "Data Structure & Algorithm Lab", PAPERCODE: "ES-CS391" },
    ],
    EE: [
      { PAPERNAME: "ELECTRIC CIRCUIT THEORY", PAPERCODE: "PC-EE 301 " },
      { PAPERNAME: "ANALOG ELECTRONICS ", PAPERCODE: " PC-EE 302 " },
      { PAPERNAME: "ELECTRO MAGNETIC FIELD THEORY", PAPERCODE: "PC-EE 303 " },
      { PAPERNAME: "ENGINEERING MECHANICS ", PAPERCODE: "ES-ME 301 " },
      { PAPERNAME: "MATHEMATICS-III ", PAPERCODE: "BS- M 301 " },
      { PAPERNAME: "BIOLOGY FOR ENGINEERS", PAPERCODE: "BS- 301 " },
      { PAPERNAME: "INDIAN CONSTOTUTION", PAPERCODE: "MC-EE 301 " },
      { PAPERNAME: "Electric circuit theory ", PAPERCODE: "PC-EE391 " },
      { PAPERNAME: "Numerical Methods laboratory", PAPERCODE: "PC-CS 391 " },
      { PAPERNAME: "Analog electronic laboratory ", PAPERCODE: "PC-EE392 " },
    ],
    EEE: [
      { PAPERNAME: "ELECTRIC CIRCUIT THEORY", PAPERCODE: "PC-EE 301 " },
      { PAPERNAME: "ANALOG ELECTRONICS ", PAPERCODE: " PC-EE 302 " },
      { PAPERNAME: "ELECTRO MAGNETIC FIELD THEORY", PAPERCODE: "PC-EE 303 " },
      { PAPERNAME: "ENGINEERING MECHANICS ", PAPERCODE: "ES-ME 301 " },
      { PAPERNAME: "MATHEMATICS-III ", PAPERCODE: "BS- M 301 " },
      { PAPERNAME: "BIOLOGY FOR ENGINEERS", PAPERCODE: "BS- 301 " },
      { PAPERNAME: "INDIAN CONSTOTUTION", PAPERCODE: "MC-EE 301 " },
      { PAPERNAME: "Electric circuit theory ", PAPERCODE: "PC-EE391 " },
      { PAPERNAME: "Numerical Methods laboratory", PAPERCODE: "PC-CS 391 " },
      { PAPERNAME: "Analog electronic laboratory ", PAPERCODE: "PC-EE392 " },
    ],
  },
  5: {
    CSE: [
      { PAPERNAME: "Software Engineering", PAPERCODE: "ESC501 " },
      { PAPERNAME: "Compiler Design", PAPERCODE: " PCC-CS501" },
      { PAPERNAME: "Operating Systems", PAPERCODE: "PCC-CS502 " },
      { PAPERNAME: "Computer Organization", PAPERCODE: " PCC-CS503" },
      {
        PAPERNAME: "Introduction to Industrial Management(Humanities III)",
        PAPERCODE: "HSMC-501",
      },
      { PAPERNAME: "Theory of Computation", PAPERCODE: "PEC-IT501A" },
      { PAPERNAME: "Artificial Intelligence", PAPERCODE: "PEC-IT501B" },
      { PAPERNAME: "Advanced Computer Architecture", PAPERCODE: " PEC-IT501C" },
      { PAPERNAME: "Computer Graphics", PAPERCODE: "PEC-IT501D" },
      { PAPERNAME: "Constitution of India", PAPERCODE: "MC-IT501 " },
      { PAPERNAME: "Software Engineering Lab", PAPERCODE: "ESC591" },
      { PAPERNAME: "Operating System Lab", PAPERCODE: "PCC-CS592" },
      { PAPERNAME: "Object Oriented Programming Lab", PAPERCODE: "PCC-CS593" },
    ],
    IT: [
      { PAPERNAME: "Software Engineering", PAPERCODE: "ESC501 " },
      { PAPERNAME: "Compiler Design", PAPERCODE: " PCC-CS501" },
      { PAPERNAME: "Operating Systems", PAPERCODE: "PCC-CS502 " },
      { PAPERNAME: "Computer Organization", PAPERCODE: " PCC-CS503" },
      {
        PAPERNAME: "Introduction to Industrial Management(Humanities III)",
        PAPERCODE: "HSMC-501",
      },
      { PAPERNAME: "Theory of Computation", PAPERCODE: "PEC-IT501A" },
      { PAPERNAME: "Artificial Intelligence", PAPERCODE: "PEC-IT501B" },
      { PAPERNAME: "Advanced Computer Architecture", PAPERCODE: " PEC-IT501C" },
      { PAPERNAME: "Computer Graphics", PAPERCODE: "PEC-IT501D" },
      { PAPERNAME: "Constitution of India", PAPERCODE: "MC-IT501 " },
      { PAPERNAME: "Software Engineering Lab", PAPERCODE: "ESC591" },
      { PAPERNAME: "Operating System Lab", PAPERCODE: "PCC-CS592" },
      { PAPERNAME: "Object Oriented Programming Lab", PAPERCODE: "PCC-CS593" },
    ],
    CSBS: [
      { PAPERNAME: "Design And Analysis of Algorithms+Lab", PAPERCODE: null },
      { PAPERNAME: "Compiler Design+ Lab,LEX & YACC", PAPERCODE: null },
      { PAPERNAME: "Fundamentals of Management", PAPERCODE: null },
      { PAPERNAME: "Business Strategy", PAPERCODE: null },
      {
        PAPERNAME: "Business Communication & Value Science – III",
        PAPERCODE: null,
      },
      { PAPERNAME: "Elective II**", PAPERCODE: null },
      { PAPERNAME: "Elective I + Lab**", PAPERCODE: null },
      { PAPERNAME: "Mini Project", PAPERCODE: null },
    ],
    ME: [
      { PAPERNAME: "Heat Transfer", PAPERCODE: "PC-ME501" },
      { PAPERNAME: " Solid Mechanics", PAPERCODE: "PC-ME502" },
      {
        PAPERNAME: "Kinematics and Theory of Machines",
        PAPERCODE: "PC-ME 503",
      },
      {
        PAPERNAME: "Humanities I(Effective Technical Communication)",
        PAPERCODE: "HM-HU501",
      },
      {
        PAPERNAME: "Essence of Indian Knowledge Tradition",
        PAPERCODE: "MC501",
      },
      {
        PAPERNAME: "Mechanical Engineering Laboratory (Thermal I)",
        PAPERCODE: "PC-ME591",
      },
      { PAPERNAME: "Machine Drawing", PAPERCODE: "PC-ME592" },
      { PAPERNAME: "Project-I", PAPERCODE: "PW-ME581" },
    ],
    ECE: [
      { PAPERNAME: "Electromagnetic Waves", PAPERCODE: "EC501" },
      { PAPERNAME: "Computer Architecture", PAPERCODE: "EC502" },
      { PAPERNAME: "Digital Communication and Stochastic", PAPERCODE: "EC503" },
      { PAPERNAME: "Digital Signal Processing ", PAPERCODE: "EC504" },
      { PAPERNAME: "Effective Technical Communication", PAPERCODE: "MC-HU501" },
      { PAPERNAME: "Nano Electronics", PAPERCODE: "PE-EC505A" },
      { PAPERNAME: "Speech and Audio Processing", PAPERCODE: "PE-EC505B" },
      { PAPERNAME: "Power Electronics", PAPERCODE: "PE-EC505C " },
      { PAPERNAME: "Scientific Computing", PAPERCODE: "PE-EC505D" },
      {
        PAPERNAME: "Soft Skill and Interpersonal Communication",
        PAPERCODE: "OE-EC506A",
      },
      {
        PAPERNAME: "Cyber Law & Intellectual Property Rights",
        PAPERCODE: "OE-EC506B",
      },
      { PAPERNAME: "Human Resource Management ", PAPERCODE: "OE-EC506C" },
      { PAPERNAME: "Electromagnetic Wave Laboratory", PAPERCODE: "EC591" },
      { PAPERNAME: "Digital Communication Laboratory", PAPERCODE: "EC592" },
      { PAPERNAME: "Digital Signal Processing Laboratory", PAPERCODE: "EC593" },
    ],
    EE: [
      { PAPERNAME: "ELECTRIC MACHINE-II", PAPERCODE: "PC-EE-501" },
      { PAPERNAME: "POWER SYSTEM-I", PAPERCODE: "PC-EE-502" },
      { PAPERNAME: "CONTROL SYSTEM", PAPERCODE: "PC-EE-503" },
      { PAPERNAME: "POWER ELECTRONICS", PAPERCODE: "PC-EE-504" },
      { PAPERNAME: "ELECTRIC MACHINE-IILABORATORY", PAPERCODE: "PC-EE 591 " },
      { PAPERNAME: "DATA STRUCTURE & ALGORITHM", PAPERCODE: "OE-EE-501A " },
      { PAPERNAME: "OBJECT ORIENTED PROGRAMMING", PAPERCODE: "OE-EE-501B" },
      { PAPERNAME: "COMPUTER ORGANISATION ", PAPERCODE: "OE-EE-501C" },
      { PAPERNAME: "HIGH VOLTAGE ENGINEERING", PAPERCODE: "PE-EE-501A" },
      { PAPERNAME: "POWER PLANT ENGINEERING", PAPERCODE: "PE-EE-501B" },
      {
        PAPERNAME: "RENEWABLE & NON CONVENTIONAL ENERGY",
        PAPERCODE: "PE-EE-501C",
      },
      { PAPERNAME: "POWER SYSTEM-I LABORATORY", PAPERCODE: "PC-EE 592" },
      { PAPERNAME: "CONTROL SYSTEM LABORATORY", PAPERCODE: " PC-EE 593" },
      { PAPERNAME: "POWER ELECTRONICS LABORATORY", PAPERCODE: " PC-EE 594" },
    ],
    EEE: [
      { PAPERNAME: "ELECTRIC MACHINE-II", PAPERCODE: "PC-EE-501" },
      { PAPERNAME: "POWER SYSTEM-I", PAPERCODE: "PC-EE-502" },
      { PAPERNAME: "CONTROL SYSTEM", PAPERCODE: "PC-EE-503" },
      { PAPERNAME: "POWER ELECTRONICS", PAPERCODE: "PC-EE-504" },
      { PAPERNAME: "ELECTRIC MACHINE-IILABORATORY", PAPERCODE: "PC-EE 591 " },
      { PAPERNAME: "DATA STRUCTURE & ALGORITHM", PAPERCODE: "OE-EE-501A " },
      { PAPERNAME: "OBJECT ORIENTED PROGRAMMING", PAPERCODE: "OE-EE-501B" },
      { PAPERNAME: "COMPUTER ORGANISATION ", PAPERCODE: "OE-EE-501C" },
      { PAPERNAME: "HIGH VOLTAGE ENGINEERING", PAPERCODE: "PE-EE-501A" },
      { PAPERNAME: "POWER PLANT ENGINEERING", PAPERCODE: "PE-EE-501B" },
      {
        PAPERNAME: "RENEWABLE & NON CONVENTIONAL ENERGY",
        PAPERCODE: "PE-EE-501C",
      },
      { PAPERNAME: "POWER SYSTEM-I LABORATORY", PAPERCODE: "PC-EE 592" },
      { PAPERNAME: "CONTROL SYSTEM LABORATORY", PAPERCODE: " PC-EE 593" },
      { PAPERNAME: "POWER ELECTRONICS LABORATORY", PAPERCODE: " PC-EE 594" },
    ],
  },
  7: {
    CSE: [
      { PAPERNAME: "Quantum Computing ", PAPERCODE: "PEC-CS701A" },
      { PAPERNAME: "Cloud Computing ", PAPERCODE: "PEC-CS701B " },
      { PAPERNAME: "Digital Signal Processing ", PAPERCODE: "PEC-CS701C" },
      {
        PAPERNAME: "Multi-agent Intelligent Systems ",
        PAPERCODE: "PEC-CS701D",
      },
      { PAPERNAME: "Machine Learning ", PAPERCODE: " PEC-CS701D" },
      {
        PAPERNAME: "Neural Networks and Deep Learning ",
        PAPERCODE: "PEC-CS702A",
      },
      { PAPERNAME: "Soft Computing", PAPERCODE: "PEC- CS702B" },
      { PAPERNAME: "Adhoc –Sensor Network ", PAPERCODE: "PEC-CS702C " },
      { PAPERNAME: "Information Theory and Coding ", PAPERCODE: "PEC-CS702D " },
      { PAPERNAME: "Cyber Security", PAPERCODE: "PEC-CS702E" },
      { PAPERNAME: "Operation Research ", PAPERCODE: "OEC-CS701A" },
      { PAPERNAME: "Examination Scheme" },
      { PAPERNAME: "Multimedia Technology ", PAPERCODE: "OEC-CS701B" },
      {
        PAPERNAME: "Introduction to Philosophical Thoughts",
        PAPERCODE: "OEC-CS701C",
      },
      {
        PAPERNAME: "Project Management and Entrepreneurship",
        PAPERCODE: " HSMC 701",
      },
      { PAPERNAME: "Project-II ", PAPERCODE: "PROJ-IT781" },
    ],
    IT: [
      { PAPERNAME: "Quantum Computing ", PAPERCODE: "PEC-CS701A" },
      { PAPERNAME: "Cloud Computing ", PAPERCODE: "PEC-CS701B " },
      { PAPERNAME: "Digital Signal Processing ", PAPERCODE: "PEC-CS701C" },
      {
        PAPERNAME: "Multi-agent Intelligent Systems ",
        PAPERCODE: "PEC-CS701D",
      },
      { PAPERNAME: "Machine Learning ", PAPERCODE: " PEC-CS701D" },
      {
        PAPERNAME: "Neural Networks and Deep Learning ",
        PAPERCODE: "PEC-CS702A",
      },
      { PAPERNAME: "Soft Computing", PAPERCODE: "PEC- CS702B" },
      { PAPERNAME: "Adhoc –Sensor Network ", PAPERCODE: "PEC-CS702C " },
      { PAPERNAME: "Information Theory and Coding ", PAPERCODE: "PEC-CS702D " },
      { PAPERNAME: "Cyber Security", PAPERCODE: "PEC-CS702E" },
      { PAPERNAME: "Operation Research ", PAPERCODE: "OEC-CS701A" },
      { PAPERNAME: "Examination Scheme" },
      { PAPERNAME: "Multimedia Technology ", PAPERCODE: "OEC-CS701B" },
      {
        PAPERNAME: "Introduction to Philosophical Thoughts",
        PAPERCODE: "OEC-CS701C",
      },
      {
        PAPERNAME: "Project Management and Entrepreneurship",
        PAPERCODE: " HSMC 701",
      },
      { PAPERNAME: "Project-II ", PAPERCODE: "PROJ-IT781" },
    ],
    CSBS: [
      {
        PAPERNAME: "Usability Design of Software Applications + Lab",
        PAPERCODE: null,
      },
      { PAPERNAME: "IT Workshop Skylab / Matlab+ Lab", PAPERCODE: null },
      { PAPERNAME: "Financial Management", PAPERCODE: null },
      { PAPERNAME: "Human Resource Management", PAPERCODE: null },
      { PAPERNAME: "Elective V", PAPERCODE: null },
      { PAPERNAME: "Elective VI+ Lab", PAPERCODE: null },
      { PAPERNAME: "Services Science & Service Operational", PAPERCODE: null },
      { PAPERNAME: "Management + Lab", PAPERCODE: null },
      { PAPERNAME: "IT Project Management + Lab", PAPERCODE: null },
    ],
    ME: [
      { PAPERNAME: "Advanced Manufacturing Technology", PAPERCODE: null },
      { PAPERNAME: "Elective III", PAPERCODE: "PE-ME701" },
      { PAPERNAME: "Elective-IV", PAPERCODE: "PE-ME702" },
      { PAPERNAME: "Open Elective- I", PAPERCODE: "OE-ME701" },
      { PAPERNAME: "Economics for Engineers", PAPERCODE: "HM-HU701" },
    ],
    ECE: [
      { PAPERNAME: "Principles of Management", PAPERCODE: "HS-HU701" },
      { PAPERNAME: "Microwave Theory and Technique", PAPERCODE: "PE-EC701A" },
      { PAPERNAME: "Satellite Communication ", PAPERCODE: "PE-EC701B" },
      {
        PAPERNAME: "Mobile Communication and Networks",
        PAPERCODE: "PE-EC701C",
      },
      { PAPERNAME: "Adaptive Signal Processing", PAPERCODE: "PE-EC702A" },
      {
        PAPERNAME: "Digital Image and Video Processing",
        PAPERCODE: "PE-EC702B",
      },
      {
        PAPERNAME: "Neural Network and Fuzzy Logic Control ",
        PAPERCODE: "PE-EC702C",
      },
      { PAPERNAME: "Embedded System", PAPERCODE: "PE-EC703A " },
      { PAPERNAME: "Wireless Sensor Networks", PAPERCODE: "PE-EC703B" },
      { PAPERNAME: "Wavelet Transforms", PAPERCODE: "PE-EC703C " },
      { PAPERNAME: "Web Technology ", PAPERCODE: "OE-EC704A" },
      { PAPERNAME: "Optimization Technique", PAPERCODE: "OE-EC704B" },
      { PAPERNAME: "Entrepreneurship", PAPERCODE: "OE-EC704C" },
      { PAPERNAME: "Project Stage I ", PAPERCODE: "EC782" },
    ],
    EE: [
      { PAPERNAME: "Electric Drive", PAPERCODE: "PC-EE 701" },
      { PAPERNAME: "Electric Drive laboratory", PAPERCODE: "PC-EE 791 " },
      { PAPERNAME: "Project stage-I", PAPERCODE: "PW-EE 781 " },
      { PAPERNAME: "Seminar", PAPERCODE: "PW-EE782 " },
    ],
    EEE: [
      {
        PAPERNAME: "Analog and digital communication",
        PAPERCODE: "PC-EEE 701",
      },
      {
        PAPERNAME: "Analog and digital Communication laboratory",
        PAPERCODE: "PC-EEE 791",
      },
      { PAPERNAME: "Project stage-I ", PAPERCODE: "PW-EEE 781" },
      { PAPERNAME: "Seminar", PAPERCODE: "PW-EEE782 " },
    ],
  },
};

export default subjectList;
